### ISSUE TITLE
Language Server for VSCode

### ISSUE THREAD

**Issue by Gold-Blend** [centrica-engineering/nucleus-language-server#1]
## Outcome

Create an extension for VSCode that allows for auto-completion for Nucleus web components 

## Scope

- [x] Create a server 
- [x] Import custom elements manifest
- [x] Setting up auto-completion using the LS 
- [x] Add to VSCode as a private extension

## TODO 

 - [x] Learn about the LSP 
 - [x] Understand the CEM
 - [x] Understand who would be able to utilise this extension
 - [x] Is it limited to VSCode?

**Comment by CalumNaughton** [comment]
# Transfer

- [ ] This issue should be transferred to the `nucleus-vscode-language-server` repository.
